# Generated by Django 5.0.4 on 2024-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=50)),
                ('user_budget', models.DecimalField(decimal_places=3, default=0.0, max_digits=13)),
            ],
        ),
    ]
